# Flask Backend & Gemini API Integration Plan

This plan outlines the steps required to transition the static frontend into a full-stack application by introducing a Python Flask backend that communicates with the Google Gemini 2.5 Pro model using the API key you provided.

## Goal

- Build a Flask server to handle backend routing and API security.
- Integrate the Google Gemini API (`gemini-2.5-pro`) to process user queries.
- Connect the existing vanilla JS frontend to the new backend to display AI responses dynamically.

## Proposed Changes

### Backend Setup (Python/Flask)
#### [NEW] `app.py`
- Initialize a basic Flask server.
- Set up a POST route `/api/chat` that receives the user's prompt as JSON.
- Configure the Gemini SDK (using the `google-generativeai` library) with your API key and map the calls to the `gemini-2.5-pro` model.
- Return the generated response back to the frontend.

#### [NEW] `requirements.txt`
- Define the necessary Python dependencies: `Flask`, `flask-cors`, `google-generativeai`, and optionally `python-dotenv` for environment variable loading.

#### [NEW] `.env`
- Securely store the provided API key: `GEMINI_API_KEY=AIzaSyBhuFOR-q-6_kOhO-zZX3FUAzjpMQvBiF8`

### Frontend Modifications
#### [MODIFY] `index.html`
- Add a new container section below the search box (or replacing the "Try Computer" grid when a search is active) to visually display the response generated by the AI model.

#### [MODIFY] `styles.css`
- Add typography and layouts for the AI's response paragraph, including placeholder loading states, to maintain the clean dark theme.

#### [MODIFY] `script.js`
- Attach an event listener to the `Ask anything...` textarea so that when the user presses `Enter` (without shift), it sends a `fetch` POST request to our Flask backend route (`/api/chat`).
- Handle the asynchronous response and inject the text into our new HTML container.

## Open Questions

> [!IMPORTANT]
> 1. **UX Flow:** When the user submits a search, should we hide the "Try Computer" suggestions grid to make room for the AI's response, or just show the response directly beneath it?
> 2. **Conversation Context:** For now, I will implement a single query-response flow (no chat memory). Let me know if you want the system to remember previous messages in the session!
> 3. **Markdown Rendering:** Gemini responses often contain markdown formatting (like bold text or code blocks). Should I add a library like `marked.js` to render the markdown visually, or just output plain text for now?

## Verification Plan

### Automated Tests
- N/A for this rapid prototype.

### Manual Verification
- We will install the Python required dependencies (`pip install -r requirements.txt`).
- Run the Flask server locally.
- Type a prompt into the UI, submit it, and verify that the Gemini API returns a response and displays it properly on the page.
